version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-forum-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # ログファイルを永続化
      - ./logs:/app/logs
      # 設定ファイルをマウント
      - ./config:/app/config:ro
    networks:
      - discord-bot-network
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  discord-bot-network:
    driver: bridge
